version: '2'

services:
  app:
    build: .
    volumes:
      - "./app:/src/app"
    working_dir: /src/app
    env_file: .env
    depends_on:
      - mongo
  mongo:
    image: mongo:3
    command: mongod --smallfiles